### ISSUE TITLE
Skopeo v0.1.29 breaks anchore-engine somehow

### ISSUE THREAD

**Issue by CameronLonsdale** [anchore/anchore-engine#59]
**Is this a request for help?**:

YES

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

BUG REPORT 

**Version of Anchore Engine and Anchore CLI if applicable**:

v0.2.1
 
**What happened**:

I tried installing anchore on fedora which uses skopeo v0.1.29 and found image analysis was failing. Centos 7 has v0.1.26.

It seems like all the analyzers start failing, here's one example:
```
anchore-engine_1  | [service:worker] 2018-06-07 05:08:25+0000 [-] [Thread-150] [anchore_engine.clients.localanchore_standalone/run_anchore_analyzers()] [ERROR] command failed with exception - command failed: cmd=/usr/lib/python2.7/site-packages/anchore/anchore-modules/analyzers/30_file_checksums.py 70b5d81549ec19aa0a10f8660ba5e1ab9966008dbb1b6c5af3d0ecc8cff88eef /tmp/1605bd31-f609-4a2f-9cbd-83604e4d8dd8 /tmp/1605bd31-f609-4a2f-9cbd-83604e4d8dd8/output /tmp/1605bd31-f609-4a2f-9cbd-83604e4d8dd8 exitcode=1 stdout=Input image name '70b5d81549ec19aa0a10f8660ba5e1ab9966008dbb1b6c5af3d0ecc8cff88eef' not found in local dockerhost or anchore DB. stderr=
```

According to the logs, skopeo was able to successfully copy an image from the docker hub.

I tried adding centos:6 as a test image for anchore to scan

**Comment by nurmi** [comment]
hi @CameronLonsdale ,

Can you share your configuration (config.yaml) and possibly some more log output from the analyzer?  This error is indicating something that shouldn't be related to skopeo (its looks more like an analyzer module failure for some reason).   It might also be worth trying the 0.2.2 (just released) verision of anchore-engine, as we've moved away from the original 'anchore' dependency, and brought the analyzer modules into the anchore-engine codebase directly.

**Comment by CameronLonsdale** [comment]
So I tried 0.2.2, different error this time:

```
[36manchore-engine_1  |[0m [service:catalog] 2018-06-11 06:53:41+0000 [-] "172.18.0.4" - - [11/Jun/2018:06:53:40 +0000] "PUT /v1/image/sha256:9ec307ee427e18d4b8976a9facaf3665f2f8f73657f8b9d39023df5ac87433ff HTTP/1.1" 200 1478 "-" "python-requests/2.17.3"
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] Traceback (most recent call last):
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 383, in process_analyzer_job
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]     resp = client.ingress_image(request)
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/clients/policy_engine/generated/api/default_api.py", line 743, in ingress_image
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]     (data) = self.ingress_image_with_http_info(ingress_request, **kwargs)  # noqa: E501
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/clients/policy_engine/generated/api/default_api.py", line 820, in ingress_image_with_http_info
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]     collection_formats=collection_formats)
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/clients/policy_engine/generated/api_client.py", line 322, in call_api
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]     _preload_content, _request_timeout)
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/clients/policy_engine/generated/api_client.py", line 153, in __call_api
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]     _request_timeout=_request_timeout)
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/clients/policy_engine/generated/api_client.py", line 365, in request
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]     body=body)
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/clients/policy_engine/generated/rest.py", line 275, in POST
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]     body=body)
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/clients/policy_engine/generated/rest.py", line 228, in request
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]     raise ApiException(http_resp=r)
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] ApiException: (500)
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] Reason: INTERNAL SERVER ERROR
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 11 Jun 2018 06:53:38 GMT', 'Content-Length': '147', 'Content-Type': 'application/problem+json', 'Server': 'TwistedWeb/17.5.0'})
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] HTTP response body: {
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   "detail": "Internal error processing image analysis import", 
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   "status": 500, 
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   "title": "Internal Server Error", 
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   "type": "about:blank"
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] }
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] 
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] 
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] Traceback (most recent call last):
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 391, in process_analyzer_job
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]     raise newerr
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] PolicyEngineClientError: Adding image to policy-engine failed - exception: (500)
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] Reason: INTERNAL SERVER ERROR
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 11 Jun 2018 06:53:38 GMT', 'Content-Length': '147', 'Content-Type': 'application/problem+json', 'Server': 'TwistedWeb/17.5.0'})
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] HTTP response body: {
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   "detail": "Internal error processing image analysis import", 
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   "status": 500, 
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   "title": "Internal Server Error", 
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-]   "type": "about:blank"
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] }
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] 
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] 
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 06:53:41+0000 [-] [Thread-14] [anchore_engine.services.analyzer/process_analyzer_job()] [ERROR] problem analyzing image - exception: Adding image to policy-engine failed - exception: (500)
[36manchore-engine_1  |[0m [service:worker] 	Reason: INTERNAL SERVER ERROR
[36manchore-engine_1  |[0m [service:worker] 	HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 11 Jun 2018 06:53:38 GMT', 'Content-Length': '147', 'Content-Type': 'application/problem+json', 'Server': 'TwistedWeb/17.5.0'})
[36manchore-engine_1  |[0m [service:worker] 	HTTP response body: {
[36manchore-engine_1  |[0m [service:worker] 	  "detail": "Internal error processing image analysis import", 
[36manchore-engine_1  |[0m [service:worker] 	  "status": 500, 
[36manchore-engine_1  |[0m [service:worker] 	  "title": "Internal Server Error", 
[36manchore-engine_1  |[0m [service:worker] 	  "type": "about:blank"
[36manchore-engine_1  |[0m [service:worker] 	}
[36manchore-engine_1  |[0m [service:worker] 	
```

**Comment by CameronLonsdale** [comment]
And here is my config (I've turned vuln updates off, i've got a pre populated database i'm using)

```
# Anchore Service Configuration File
#

# General system-wide configuration options, these should not need to
# be altered for basic operation
#
# service_dir: '/config'
# tmp_dir: '/tmp'
log_level: 'DEBUG'
#log_level: 'INFO'
cleanup_images: True
# allow_awsecr_iam_auto: False
# docker_conn: 'unix://var/run/docker.sock'
# docker_conn_timeout: 600
host_id: 'dockerhostid-${ANCHORE_HOST_ID}'
internal_ssl_verify: False
auto_restart_services: True
#catalog_endpoint: 'http://${ANCHORE_HOST_ID}:8082/v1'
#

# Uncomment if you would like to enable prometheus metrics routes in
# anchore-engine (enables metric gathering and /metrics route for all
# services)
#
#metrics: 
#  enabled: True
#

# Uncomment if you have a local endpoint that can accept
# notifications from the anchore-engine, as configured below
#
#webhooks:
#  webhook_user: 'user'
#  webhook_pass: 'pass'
#  ssl_verify: False
#  general:
#    url: 'http://localhost:9090/general/<notification_type>/<userId>'
#  policy_eval:
#    url: 'http://localhost:9090/policy_eval/<userId>'
#    webhook_user: 'mehuser'
#    webhook_pass: 'mehpass'
#

#
# A feeds section is available for override, but shouldn't be
# needed. By default, the 'admin' credentials are used if present,
# otherwise anonymous access for feed sync is used
#
feeds:
 selective_sync:
   # If enabled only sync specific feeds instead of all.
   enabled: True
   feeds:
     # No feed updates
     vulnerabilities: False
     # Warning: enabling the package sync causes the service to require much
     #   more memory to do process the significant data volume. We recommend at least 4GB available for the container
     packages: False
 anonymous_user_username: anon@ancho.re
 anonymous_user_password: pbiU2RYZ2XrmYQ
 url: 'https://ancho.re/v1/service/feeds'
 client_url: 'https://ancho.re/v1/account/users'
 token_url: 'https://ancho.re/oauth/token'
 connection_timeout_seconds: 3
 read_timeout_seconds: 60


credentials:
  users:
     admin:
       password: 'foobar'
       email: 'admin@myemail.com'
       external_service_auths:
       #  anchoreio:
       #    anchorecli:
       #      auth: 'myanchoreiouser:myanchoreiopass'
       #auto_policy_sync: True

  database:
    db_connect: 'postgresql+pg8000://postgres:@anchore-db:5432/postgres'
    db_connect_args:
      timeout: 120
      ssl: False
    db_pool_size: 30
    db_pool_max_overflow: 100

services:
  apiext:
    enabled: True
    require_auth: True
    endpoint_hostname: '${ANCHORE_HOST_ID}'
    listen: '0.0.0.0'
    port: 8228
  kubernetes_webhook:
    enabled: True
    require_auth: False
    endpoint_hostname: '${ANCHORE_HOST_ID}'
    listen: '0.0.0.0'
    port: 8338
  catalog:
    enabled: True
    require_auth: True
    endpoint_hostname: '${ANCHORE_HOST_ID}'
    listen: '0.0.0.0'
    port: 8082
    archive:
      compression:
        enabled: False
        min_size_kbytes: 100
      storage_driver:
        name: db
        config: {}
    cycle_timer_seconds: '1'
    cycle_timers:
      image_watcher: 3600
      policy_eval: 3600
      vulnerability_scan: 14400
      analyzer_queue: 1
      notifications: 30
      service_watcher: 15
      policy_bundle_sync: 300
      repo_watcher: 60
  simplequeue:
    enabled: True
    require_auth: True
    endpoint_hostname: '${ANCHORE_HOST_ID}'
    listen: '0.0.0.0'
    port: 8083
  analyzer:
    enabled: True
    require_auth: True
    cycle_timer_seconds: 1
    max_threads: 1
    analyzer_driver: 'nodocker'
    endpoint_hostname: '${ANCHORE_HOST_ID}'
    listen: '0.0.0.0'
    port: 8084
  policy_engine:
    enabled: True
    require_auth: True
    endpoint_hostname: '${ANCHORE_HOST_ID}'
    listen: '0.0.0.0'
    port: 8087
    cycle_timer_seconds: 1
    cycle_timers:
      feed_sync: 21600 # 6 hours between feed syncs
      feed_sync_checker: 3600 # 1 hour between checks to see if there needs to be a task queued
```

**Comment by CameronLonsdale** [comment]
Looks like the policy engine died from this
```
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 07:09:23+0000 [-] [Thread-42] [anchore_engine.clients.common/get_service_endpoint()] [DEBUG] got endpoint (catalog): http://anchore-engine:8082/v1
[36manchore-engine_1  |[0m [service:worker] 2018-06-11 07:09:23+0000 [-] [Thread-42] [anchore_engine.clients.common/get_service_endpoint()] [DEBUG] got endpoint (catalog): http://anchore-engine:8082/v1
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [_GenericHTTPChannelProtocol,0,172.18.0.3] [PoolThread-twisted.internet.reactor-0] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Loading image files
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-] Traceback (most recent call last):
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 497, in _load_image_analysis
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]     result = loader.load()
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/loaders.py", line 119, in load
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]     image.fs = self.load_fsdump(analysis_report)
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/loaders.py", line 447, in load_fsdump
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]     path_map = {path: json.loads(value) for path, value in all_infos.items()}
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-] AttributeError: 'list' object has no attribute 'items'
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [_GenericHTTPChannelProtocol,0,172.18.0.3] [PoolThread-twisted.internet.reactor-0] [anchore_engine.services.policy_engine.engine.logs/exception()] [ERROR] Exception in image loader
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-] Traceback (most recent call last):
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 452, in execute
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]     image_obj = self._load_image_analysis()
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 497, in _load_image_analysis
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]     result = loader.load()
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/loaders.py", line 119, in load
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]     image.fs = self.load_fsdump(analysis_report)
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/loaders.py", line 447, in load_fsdump
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-]     path_map = {path: json.loads(value) for path, value in all_infos.items()}
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [-] AttributeError: 'list' object has no attribute 'items'
[36manchore-engine_1  |[0m [service:policy-engine] 2018-06-11 07:09:23+0000 [_GenericHTTPChannelProtocol,0,172.18.0.3] [PoolThread-twisted.internet.reactor-0] [anchore_engine.services.policy_engine.engine.logs/exception()] [ERROR] Error loading and scanning image: 70b5d81549ec19aa0a10f8660ba5e1ab9966008dbb1b6c5af3d0ecc8cff88eef
```

**Comment by CameronLonsdale** [comment]
Okay I got it to work on fedora and v0.2.2 of anchore. v0.2.2 seemed to fix the original issue. The second issue seemed to be fixed by this:
```
# EXPOSE 8228
EXPOSE 8228 8338 8087 8082
```
I wasnt exposing all the ports in the dockerfile - a misunderstanding in how anchore works :P I thought I didnt need them all

**Comment by zhill** [comment]
@CameronLonsdale can this issue be closed or are there still things to address?

**Comment by CameronLonsdale** [comment]
@zhill this can be closed
